import { lazy, type ComponentType } from 'react';
import { TrendingUp, TrendingDown, Percent, ArrowUpDown, DollarSign, Calculator, LineChart, Activity, Wallet, BarChart3, Clock, Grid3X3, TrendingUpDown, Receipt, Landmark, Mountain, PiggyBank, List, Trophy } from 'lucide-react';
import type { WidgetDefBase, WidgetCategory } from '@quovibe/shared';

export interface WidgetDef extends WidgetDefBase {
  component: ComponentType<object>;
  icon?: ComponentType<{ className?: string }>;
}

export const CATEGORY_COLORS: Record<WidgetCategory, string> = {
  performance: '#3b82f6',
  reports: '#22c55e',
  chart: '#a855f7',
  risk: '#ef4444',
  info: '#94a3b8',
};

export const WIDGET_REGISTRY: WidgetDef[] = [
  {
    type: 'market-value',
    i18nKey: 'widgetTypes.market-value',
    descriptionKey: 'catalog.desc.market-value',
    qualifierKey: 'widget.qualifier.now',
    category: 'performance',
    zone: 'detail',
    defaultSpan: 1,
    defaultConfig: {},
    capabilities: { hasDataSeries: true, hasPeriodOverride: true, hasCustomOptions: false },
    icon: Wallet,
    component: lazy(() => import('@/components/domain/widgets/WidgetMarketValue')),
  },
  {
    type: 'ttwror',
    i18nKey: 'widgetTypes.ttwror',
    descriptionKey: 'catalog.desc.ttwror',
    qualifierKey: 'widget.qualifier.cumulative',
    category: 'performance',
    zone: 'detail',
    defaultSpan: 1,
    defaultConfig: {},
    capabilities: { hasDataSeries: true, hasPeriodOverride: true, hasCustomOptions: false },
    icon: TrendingUp,
    component: lazy(() => import('@/components/domain/widgets/WidgetTtwror')),
  },
  {
    type: 'ttwror-pa',
    i18nKey: 'widgetTypes.ttwror-pa',
    descriptionKey: 'catalog.desc.ttwror-pa',
    qualifierKey: 'widget.qualifier.annualized',
    category: 'performance',
    zone: 'detail',
    defaultSpan: 1,
    defaultConfig: {},
    capabilities: { hasDataSeries: true, hasPeriodOverride: true, hasCustomOptions: false },
    icon: TrendingUp,
    component: lazy(() => import('@/components/domain/widgets/WidgetTtwrorPa')),
  },
  {
    type: 'irr',
    i18nKey: 'widgetTypes.irr',
    descriptionKey: 'catalog.desc.irr',
    qualifierKey: 'widget.qualifier.annualized',
    category: 'performance',
    zone: 'detail',
    defaultSpan: 1,
    defaultConfig: {},
    capabilities: { hasDataSeries: true, hasPeriodOverride: true, hasCustomOptions: false },
    icon: Percent,
    component: lazy(() => import('@/components/domain/widgets/WidgetIrr')),
  },
  {
    type: 'delta',
    i18nKey: 'widgetTypes.delta',
    descriptionKey: 'catalog.desc.delta',
    qualifierKey: 'widget.qualifier.period',
    category: 'performance',
    zone: 'detail',
    defaultSpan: 1,
    defaultConfig: {},
    capabilities: { hasDataSeries: true, hasPeriodOverride: true, hasCustomOptions: false },
    icon: ArrowUpDown,
    component: lazy(() => import('@/components/domain/widgets/WidgetDelta')),
  },
  {
    type: 'absolute-performance',
    i18nKey: 'widgetTypes.absolute-performance',
    descriptionKey: 'catalog.desc.absolute-performance',
    qualifierKey: 'widget.qualifier.period',
    category: 'performance',
    zone: 'detail',
    defaultSpan: 1,
    defaultConfig: {},
    capabilities: { hasDataSeries: true, hasPeriodOverride: true, hasCustomOptions: false },
    icon: Activity,
    component: lazy(() => import('@/components/domain/widgets/WidgetAbsolutePerformance')),
  },
  {
    type: 'absolute-change',
    i18nKey: 'widgetTypes.absolute-change',
    descriptionKey: 'catalog.desc.absolute-change',
    qualifierKey: 'widget.qualifier.period',
    category: 'performance',
    zone: 'detail',
    defaultSpan: 1,
    defaultConfig: {},
    capabilities: { hasDataSeries: true, hasPeriodOverride: true, hasCustomOptions: false },
    icon: DollarSign,
    component: lazy(() => import('@/components/domain/widgets/WidgetAbsoluteChange')),
  },
  {
    type: 'calculation-compact',
    i18nKey: 'widgetTypes.calculation-compact',
    descriptionKey: 'catalog.desc.calculation-compact',
    qualifierKey: null,
    category: 'performance',
    zone: 'detail',
    defaultSpan: 1,
    capabilities: { hasDataSeries: true, hasPeriodOverride: true, hasCustomOptions: false },
    defaultConfig: {
      dataSeries: { type: 'portfolio', preTax: false },
      periodOverride: null,
      options: {},
    },
    icon: Calculator,
    component: lazy(() => import('@/components/domain/widgets/WidgetCalculationCompact')),
  },
  {
    type: 'max-drawdown',
    i18nKey: 'widgetTypes.max-drawdown',
    descriptionKey: 'catalog.desc.max-drawdown',
    qualifierKey: 'widget.qualifier.period',
    category: 'risk',
    zone: 'detail',
    defaultSpan: 1,
    defaultConfig: {},
    capabilities: { hasDataSeries: true, hasPeriodOverride: true, hasCustomOptions: false },
    icon: TrendingDown,
    component: lazy(() => import('@/components/domain/widgets/WidgetMaxDrawdown')),
  },
  {
    type: 'current-drawdown',
    i18nKey: 'widgetTypes.current-drawdown',
    descriptionKey: 'catalog.desc.current-drawdown',
    qualifierKey: 'widget.qualifier.now',
    category: 'risk',
    zone: 'detail',
    defaultSpan: 1,
    defaultConfig: {},
    capabilities: { hasDataSeries: true, hasPeriodOverride: true, hasCustomOptions: false },
    icon: TrendingDown,
    component: lazy(() => import('@/components/domain/widgets/WidgetCurrentDrawdown')),
  },
  {
    type: 'max-drawdown-duration',
    i18nKey: 'widgetTypes.max-drawdown-duration',
    descriptionKey: 'catalog.desc.max-drawdown-duration',
    qualifierKey: 'widget.qualifier.period',
    category: 'risk',
    zone: 'detail',
    defaultSpan: 1,
    defaultConfig: {},
    capabilities: { hasDataSeries: true, hasPeriodOverride: true, hasCustomOptions: false },
    icon: Clock,
    component: lazy(() => import('@/components/domain/widgets/WidgetMaxDrawdownDuration')),
  },
  {
    type: 'drawdown-chart',
    i18nKey: 'widgetTypes.drawdown-chart',
    descriptionKey: 'catalog.desc.drawdown-chart',
    qualifierKey: null,
    category: 'chart',
    zone: 'chart',
    defaultSpan: 3,
    defaultConfig: {},
    capabilities: { hasDataSeries: true, hasPeriodOverride: true, hasCustomOptions: false },
    icon: BarChart3,
    component: lazy(() => import('@/components/domain/widgets/WidgetDrawdownChart')),
  },
  {
    type: 'volatility',
    i18nKey: 'widgetTypes.volatility',
    descriptionKey: 'catalog.desc.volatility',
    qualifierKey: 'widget.qualifier.period',
    category: 'risk',
    zone: 'detail',
    defaultSpan: 1,
    defaultConfig: {},
    capabilities: { hasDataSeries: true, hasPeriodOverride: true, hasCustomOptions: false },
    icon: Activity,
    component: lazy(() => import('@/components/domain/widgets/WidgetVolatility')),
  },
  {
    type: 'semivariance',
    i18nKey: 'widgetTypes.semivariance',
    descriptionKey: 'catalog.desc.semivariance',
    qualifierKey: 'widget.qualifier.period',
    category: 'risk',
    zone: 'detail',
    defaultSpan: 1,
    defaultConfig: {},
    capabilities: { hasDataSeries: true, hasPeriodOverride: true, hasCustomOptions: false },
    icon: Activity,
    component: lazy(() => import('@/components/domain/widgets/WidgetSemivariance')),
  },
  {
    type: 'sharpe-ratio',
    i18nKey: 'widgetTypes.sharpe-ratio',
    descriptionKey: 'catalog.desc.sharpe-ratio',
    qualifierKey: 'widget.qualifier.period',
    category: 'risk',
    zone: 'detail',
    defaultSpan: 1,
    defaultConfig: { options: { riskFreeRate: 0 } },
    capabilities: { hasDataSeries: true, hasPeriodOverride: true, hasCustomOptions: true },
    icon: Activity,
    component: lazy(() => import('@/components/domain/widgets/WidgetSharpeRatio')),
  },
  {
    type: 'perf-chart',
    i18nKey: 'widgetTypes.perf-chart',
    descriptionKey: 'catalog.desc.perf-chart',
    qualifierKey: null,
    category: 'chart',
    zone: 'chart',
    defaultSpan: 3,
    defaultConfig: {},
    capabilities: { hasDataSeries: true, hasPeriodOverride: true, hasCustomOptions: false },
    icon: LineChart,
    component: lazy(() => import('@/components/domain/widgets/WidgetPerfChart')),
  },
  {
    type: 'returns-heatmap',
    i18nKey: 'widgetTypes.returns-heatmap',
    descriptionKey: 'catalog.desc.returns-heatmap',
    qualifierKey: null,
    category: 'chart',
    zone: 'chart',
    defaultSpan: 3,
    defaultConfig: {},
    capabilities: { hasDataSeries: true, hasPeriodOverride: true, hasCustomOptions: false },
    icon: Grid3X3,
    component: lazy(() => import('@/components/domain/widgets/WidgetReturnsHeatmap')),
  },
  {
    type: 'benchmark-comparison',
    i18nKey: 'widgetTypes.benchmark-comparison',
    descriptionKey: 'catalog.desc.benchmark-comparison',
    qualifierKey: null,
    category: 'performance',
    zone: 'detail',
    defaultSpan: 1,
    defaultConfig: { options: {} },
    capabilities: { hasDataSeries: false, hasPeriodOverride: true, hasCustomOptions: true },
    icon: BarChart3,
    component: lazy(() => import('@/components/domain/widgets/WidgetBenchmarkComparison')),
  },
  {
    type: 'movers',
    i18nKey: 'widgetTypes.movers',
    descriptionKey: 'catalog.desc.movers',
    qualifierKey: null,
    category: 'performance',
    zone: 'detail',
    defaultSpan: 2,
    defaultConfig: {},
    capabilities: { hasDataSeries: true, hasPeriodOverride: true, hasCustomOptions: false },
    icon: TrendingUpDown,
    component: lazy(() => import('@/components/domain/widgets/WidgetMovers')),
  },
  {
    type: 'cost-tax-drag',
    i18nKey: 'widgetTypes.cost-tax-drag',
    descriptionKey: 'catalog.desc.cost-tax-drag',
    qualifierKey: null,
    category: 'performance',
    zone: 'detail',
    defaultSpan: 2,
    defaultConfig: {},
    capabilities: { hasDataSeries: true, hasPeriodOverride: true, hasCustomOptions: false },
    icon: Receipt,
    component: lazy(() => import('@/components/domain/widgets/WidgetCostTaxDrag')),
  },
  {
    type: 'cash-drag',
    i18nKey: 'widgetTypes.cash-drag',
    descriptionKey: 'catalog.desc.cash-drag',
    qualifierKey: 'widget.qualifier.now',
    category: 'performance',
    zone: 'detail',
    defaultSpan: 1,
    defaultConfig: {},
    capabilities: { hasDataSeries: false, hasPeriodOverride: false, hasCustomOptions: false },
    icon: Landmark,
    component: lazy(() => import('@/components/domain/widgets/WidgetCashDrag')),
  },
  {
    type: 'all-time-high',
    i18nKey: 'widgetTypes.all-time-high',
    descriptionKey: 'catalog.desc.all-time-high',
    qualifierKey: null,
    category: 'performance',
    zone: 'detail',
    defaultSpan: 1,
    defaultConfig: {},
    capabilities: { hasDataSeries: false, hasPeriodOverride: false, hasCustomOptions: false },
    icon: Mountain,
    component: lazy(() => import('@/components/domain/widgets/WidgetAllTimeHigh')),
  },
  {
    type: 'distance-from-ath',
    i18nKey: 'widgetTypes.distance-from-ath',
    descriptionKey: 'catalog.desc.distance-from-ath',
    qualifierKey: null, // period override shifts currentMV endpoint, not a fixed period label
    category: 'risk',
    zone: 'detail',
    defaultSpan: 1,
    defaultConfig: {},
    capabilities: { hasDataSeries: false, hasPeriodOverride: true, hasCustomOptions: false },
    icon: TrendingDown,
    component: lazy(() => import('@/components/domain/widgets/WidgetDistanceFromATH')),
  },
  {
    type: 'invested-capital',
    i18nKey: 'widgetTypes.invested-capital',
    descriptionKey: 'catalog.desc.invested-capital',
    qualifierKey: 'widget.qualifier.period',
    category: 'performance',
    zone: 'detail',
    defaultSpan: 1,
    defaultConfig: {},
    capabilities: { hasDataSeries: false, hasPeriodOverride: true, hasCustomOptions: false },
    icon: PiggyBank,
    component: lazy(() => import('@/components/domain/widgets/WidgetInvestedCapital')),
  },
  {
    type: 'watchlist',
    i18nKey: 'widgetTypes.watchlist',
    descriptionKey: 'catalog.desc.watchlist',
    qualifierKey: null,
    category: 'info',
    zone: 'detail',
    defaultSpan: 1,
    defaultConfig: { options: { watchlistId: null } },
    capabilities: { hasDataSeries: false, hasPeriodOverride: false, hasCustomOptions: true },
    icon: List,
    component: lazy(() => import('@/components/domain/widgets/WidgetWatchlist')),
  },
  {
    type: 'top-holdings',
    i18nKey: 'widgetTypes.top-holdings',
    descriptionKey: 'catalog.desc.top-holdings',
    qualifierKey: null,
    category: 'info',
    zone: 'detail',
    defaultSpan: 2,
    defaultConfig: {},
    capabilities: { hasDataSeries: false, hasPeriodOverride: true, hasCustomOptions: false },
    icon: Trophy,
    component: lazy(() => import('@/components/domain/widgets/WidgetTopHoldings')),
  },
];

/** Look up a widget definition by type string */
export function getWidgetDef(type: string): WidgetDef | undefined {
  return WIDGET_REGISTRY.find((w) => w.type === type);
}

/** Classify a widget type into its dashboard zone */
export function getWidgetZone(type: string): 'chart' | 'detail' {
  const def = getWidgetDef(type);
  return def?.zone ?? 'detail';
}

/** Chart widget types for zone filtering */
export const CHART_WIDGET_TYPES = new Set(
  WIDGET_REGISTRY.filter((w) => w.zone === 'chart').map((w) => w.type),
);
