// packages/shared/src/csv/type-aliases.ts
import { TransactionType } from '../enums';

/**
 * Multilingual alias map for transaction types.
 * Keys are lowercase aliases, values are TransactionType enum values.
 * This map is used by the CSV normalizer to resolve user-facing type strings.
 *
 * The 8-language baseline matches the upstream exporter labels verbatim
 * (`labels_*.properties` in the source). Common-language synonyms remain as
 * fallbacks for non-PP brokers that emit variant forms; the verbatim entries
 * are listed second per language so they win on Map insertion semantics.
 */
export const transactionTypeAliases: ReadonlyMap<string, TransactionType> = new Map([
  // ── English ──
  ['buy', TransactionType.BUY],
  ['sell', TransactionType.SELL],
  ['dividend', TransactionType.DIVIDEND],
  ['deposit', TransactionType.DEPOSIT],
  ['removal', TransactionType.REMOVAL],
  ['withdrawal', TransactionType.REMOVAL],
  ['interest', TransactionType.INTEREST],
  ['interest charge', TransactionType.INTEREST_CHARGE],
  ['fees', TransactionType.FEES],
  ['fee', TransactionType.FEES],
  ['fees refund', TransactionType.FEES_REFUND],
  ['taxes', TransactionType.TAXES],
  ['tax', TransactionType.TAXES],
  ['tax refund', TransactionType.TAX_REFUND],
  ['delivery (inbound)', TransactionType.DELIVERY_INBOUND],
  ['delivery (outbound)', TransactionType.DELIVERY_OUTBOUND],
  ['delivery inbound', TransactionType.DELIVERY_INBOUND],
  ['delivery outbound', TransactionType.DELIVERY_OUTBOUND],
  ['transfer (inbound)', TransactionType.TRANSFER_BETWEEN_ACCOUNTS],
  ['transfer (outbound)', TransactionType.TRANSFER_BETWEEN_ACCOUNTS],

  // ── German ──
  ['kauf', TransactionType.BUY],
  ['verkauf', TransactionType.SELL],
  ['dividende', TransactionType.DIVIDEND],
  ['einlage', TransactionType.DEPOSIT],
  ['entnahme', TransactionType.REMOVAL],
  ['zinsen', TransactionType.INTEREST],
  ['zinsbelastung', TransactionType.INTEREST_CHARGE],
  ['gebühren', TransactionType.FEES],
  ['gebuehren', TransactionType.FEES],
  ['gebührenerstattung', TransactionType.FEES_REFUND],
  ['steuern', TransactionType.TAXES],
  ['steuerrückerstattung', TransactionType.TAX_REFUND],
  ['steuererstattung', TransactionType.TAX_REFUND],
  ['einlieferung', TransactionType.DELIVERY_INBOUND],
  ['auslieferung', TransactionType.DELIVERY_OUTBOUND],
  ['umbuchung (eingang)', TransactionType.TRANSFER_BETWEEN_ACCOUNTS],
  ['umbuchung (ausgang)', TransactionType.TRANSFER_BETWEEN_ACCOUNTS],

  // ── French ──
  ['achat', TransactionType.BUY],
  ['vente', TransactionType.SELL],
  ['dividendes', TransactionType.DIVIDEND],
  ['dividende', TransactionType.DIVIDEND],
  ['dépôt', TransactionType.DEPOSIT],
  ['depot', TransactionType.DEPOSIT],
  ['retrait', TransactionType.REMOVAL],
  ['intérêts', TransactionType.INTEREST],
  ['interets', TransactionType.INTEREST],
  ["frais d'intérêts", TransactionType.INTEREST_CHARGE],
  ["frais d'interets", TransactionType.INTEREST_CHARGE],
  ['frais', TransactionType.FEES],
  ['remboursement de frais', TransactionType.FEES_REFUND],
  ['remboursement frais', TransactionType.FEES_REFUND],
  ['impôts / taxes', TransactionType.TAXES],
  ['impots / taxes', TransactionType.TAXES],
  ['impôts', TransactionType.TAXES],
  ['impots', TransactionType.TAXES],
  ['remboursement impôts / taxes', TransactionType.TAX_REFUND],
  ['remboursement impots / taxes', TransactionType.TAX_REFUND],
  ['remboursement impôts', TransactionType.TAX_REFUND],
  ['remboursement impots', TransactionType.TAX_REFUND],
  ['distribution (entrante)', TransactionType.DELIVERY_INBOUND],
  ['distribution (sortante)', TransactionType.DELIVERY_OUTBOUND],
  ['livraison entrante', TransactionType.DELIVERY_INBOUND],
  ['livraison sortante', TransactionType.DELIVERY_OUTBOUND],
  ['transfert (entrant)', TransactionType.TRANSFER_BETWEEN_ACCOUNTS],
  ['transfert (sortant)', TransactionType.TRANSFER_BETWEEN_ACCOUNTS],

  // ── Italian ──
  ['compra', TransactionType.BUY],
  ['acquisto', TransactionType.BUY],
  ['vendi', TransactionType.SELL],
  ['vendita', TransactionType.SELL],
  ['dividendo', TransactionType.DIVIDEND],
  ['deposito', TransactionType.DEPOSIT],
  ['prelievo', TransactionType.REMOVAL],
  ['interessi', TransactionType.INTEREST],
  ['interessi passivi', TransactionType.INTEREST_CHARGE],
  ['addebito interessi', TransactionType.INTEREST_CHARGE],
  ['commissioni', TransactionType.FEES],
  ['rimborso commissioni', TransactionType.FEES_REFUND],
  ['tasse', TransactionType.TAXES],
  ['rimborso tasse', TransactionType.TAX_REFUND],
  ['trasferimento titoli (in entrata)', TransactionType.DELIVERY_INBOUND],
  ['trasferimento titoli (in uscita)', TransactionType.DELIVERY_OUTBOUND],
  ['consegna in entrata', TransactionType.DELIVERY_INBOUND],
  ['consegna in uscita', TransactionType.DELIVERY_OUTBOUND],
  ['trasferimento (in entrata)', TransactionType.TRANSFER_BETWEEN_ACCOUNTS],
  ['trasferimento (in uscita)', TransactionType.TRANSFER_BETWEEN_ACCOUNTS],

  // ── Spanish ──
  ['comprar', TransactionType.BUY],
  ['venta', TransactionType.SELL],
  ['vender', TransactionType.SELL],
  ['depósito', TransactionType.DEPOSIT],
  ['retirada', TransactionType.REMOVAL],
  ['retiro', TransactionType.REMOVAL],
  ['intereses', TransactionType.INTEREST],
  ['interés', TransactionType.INTEREST],
  ['interes', TransactionType.INTEREST],
  ['cargo por intereses', TransactionType.INTEREST_CHARGE],
  ['comisiones', TransactionType.FEES],
  ['reembolso de comisiones', TransactionType.FEES_REFUND],
  ['reembolso comisiones', TransactionType.FEES_REFUND],
  ['impuestos', TransactionType.TAXES],
  ['devolución de impuestos', TransactionType.TAX_REFUND],
  ['devolucion de impuestos', TransactionType.TAX_REFUND],
  ['reembolso impuestos', TransactionType.TAX_REFUND],
  ['entrega (entrante)', TransactionType.DELIVERY_INBOUND],
  ['entrega (saliente)', TransactionType.DELIVERY_OUTBOUND],
  ['entrega entrante', TransactionType.DELIVERY_INBOUND],
  ['entrega saliente', TransactionType.DELIVERY_OUTBOUND],
  ['transferencia (entrada)', TransactionType.TRANSFER_BETWEEN_ACCOUNTS],
  ['transferencia (salida)', TransactionType.TRANSFER_BETWEEN_ACCOUNTS],
  ['traspaso (entrada)', TransactionType.SECURITY_TRANSFER],
  ['traspaso (salida)', TransactionType.SECURITY_TRANSFER],

  // ── Dutch ──
  ['aankoop', TransactionType.BUY],
  ['kopen', TransactionType.BUY],
  ['verkoop', TransactionType.SELL],
  ['verkopen', TransactionType.SELL],
  ['dividend', TransactionType.DIVIDEND],
  ['storting', TransactionType.DEPOSIT],
  ['onttrekking', TransactionType.REMOVAL],
  ['opname', TransactionType.REMOVAL],
  ['creditrente', TransactionType.INTEREST],
  ['rente', TransactionType.INTEREST],
  ['debetrente', TransactionType.INTEREST_CHARGE],
  ['rentelast', TransactionType.INTEREST_CHARGE],
  ['kosten', TransactionType.FEES],
  ['terugbetaling kosten', TransactionType.FEES_REFUND],
  ['kostenvergoeding', TransactionType.FEES_REFUND],
  ['belasting', TransactionType.TAXES],
  ['belastingen', TransactionType.TAXES],
  ['belastingteruggave', TransactionType.TAX_REFUND],
  ['inkomende levering', TransactionType.DELIVERY_INBOUND],
  ['uitgaande levering', TransactionType.DELIVERY_OUTBOUND],
  ['inlevering', TransactionType.DELIVERY_INBOUND],
  ['uitlevering', TransactionType.DELIVERY_OUTBOUND],
  ['inkomende overboeking', TransactionType.TRANSFER_BETWEEN_ACCOUNTS],
  ['uitgaande overboeking', TransactionType.TRANSFER_BETWEEN_ACCOUNTS],

  // ── Polish ──
  ['kupno', TransactionType.BUY],
  ['sprzedaj', TransactionType.SELL],
  ['sprzedaż', TransactionType.SELL],
  ['sprzedaz', TransactionType.SELL],
  ['dywidenda', TransactionType.DIVIDEND],
  ['depozyt', TransactionType.DEPOSIT],
  ['wpłata', TransactionType.DEPOSIT],
  ['wplata', TransactionType.DEPOSIT],
  ['wypłata', TransactionType.REMOVAL],
  ['wyplata', TransactionType.REMOVAL],
  ['odsetki', TransactionType.INTEREST],
  ['opłata odsetkowa', TransactionType.INTEREST_CHARGE],
  ['oplata odsetkowa', TransactionType.INTEREST_CHARGE],
  ['obciążenie odsetkowe', TransactionType.INTEREST_CHARGE],
  ['obciazenie odsetkowe', TransactionType.INTEREST_CHARGE],
  ['opłaty', TransactionType.FEES],
  ['oplaty', TransactionType.FEES],
  ['zwrot opłat', TransactionType.FEES_REFUND],
  ['zwrot oplat', TransactionType.FEES_REFUND],
  ['podatki', TransactionType.TAXES],
  ['zwrot podatku', TransactionType.TAX_REFUND],
  ['dostawa (przychodząca)', TransactionType.DELIVERY_INBOUND],
  ['dostawa (przychodzaca)', TransactionType.DELIVERY_INBOUND],
  ['dostawa przychodząca', TransactionType.DELIVERY_INBOUND],
  ['dostawa przychodzaca', TransactionType.DELIVERY_INBOUND],
  ['dostawa (wychodząca)', TransactionType.DELIVERY_OUTBOUND],
  ['dostawa (wychodzaca)', TransactionType.DELIVERY_OUTBOUND],
  ['dostawa wychodząca', TransactionType.DELIVERY_OUTBOUND],
  ['dostawa wychodzaca', TransactionType.DELIVERY_OUTBOUND],
  ['transfer (przychodzący)', TransactionType.TRANSFER_BETWEEN_ACCOUNTS],
  ['transfer (przychodzacy)', TransactionType.TRANSFER_BETWEEN_ACCOUNTS],
  ['transfer (wychodzący)', TransactionType.TRANSFER_BETWEEN_ACCOUNTS],
  ['transfer (wychodzacy)', TransactionType.TRANSFER_BETWEEN_ACCOUNTS],

  // ── Portuguese ──
  ['comprar', TransactionType.BUY],
  ['vender', TransactionType.SELL],
  ['venda', TransactionType.SELL],
  ['dividendo', TransactionType.DIVIDEND],
  ['depósito', TransactionType.DEPOSIT],
  ['depositar', TransactionType.DEPOSIT],
  ['levantamento', TransactionType.REMOVAL],
  ['juros', TransactionType.INTEREST],
  ['encargos de juros', TransactionType.INTEREST_CHARGE],
  ['encargo de juros', TransactionType.INTEREST_CHARGE],
  ['comissões', TransactionType.FEES],
  ['comissoes', TransactionType.FEES],
  ['taxas', TransactionType.FEES],
  ['reembolso de comissões', TransactionType.FEES_REFUND],
  ['reembolso de comissoes', TransactionType.FEES_REFUND],
  ['reembolso taxas', TransactionType.FEES_REFUND],
  ['impostos', TransactionType.TAXES],
  ['reembolso de impostos', TransactionType.TAX_REFUND],
  ['reembolso impostos', TransactionType.TAX_REFUND],
  ['entrega (entrada)', TransactionType.DELIVERY_INBOUND],
  ['entrega entrada', TransactionType.DELIVERY_INBOUND],
  ['entrega (saída)', TransactionType.DELIVERY_OUTBOUND],
  ['entrega (saida)', TransactionType.DELIVERY_OUTBOUND],
  ['entrega saída', TransactionType.DELIVERY_OUTBOUND],
  ['entrega saida', TransactionType.DELIVERY_OUTBOUND],
  ['transferência (entrada)', TransactionType.TRANSFER_BETWEEN_ACCOUNTS],
  ['transferencia (entrada)', TransactionType.TRANSFER_BETWEEN_ACCOUNTS],
  ['transferência (saída)', TransactionType.TRANSFER_BETWEEN_ACCOUNTS],
  ['transferencia (saida)', TransactionType.TRANSFER_BETWEEN_ACCOUNTS],

  // ── Direct enum values (users may paste the raw type) ──
  ['delivery_inbound', TransactionType.DELIVERY_INBOUND],
  ['delivery_outbound', TransactionType.DELIVERY_OUTBOUND],
  ['interest_charge', TransactionType.INTEREST_CHARGE],
  ['fees_refund', TransactionType.FEES_REFUND],
  ['tax_refund', TransactionType.TAX_REFUND],
  ['transfer_between_accounts', TransactionType.TRANSFER_BETWEEN_ACCOUNTS],
  ['security_transfer', TransactionType.SECURITY_TRANSFER],
]);
